<?php
/**
 * Created by PhpStorm.
 * User: paskuale
 * Date: 27/09/18
 * Time: 9.21
 */

namespace paskuale75\yii2_skebby\components;

use Yii;
use yii\base\Component;





class SmsSkebby extends Component{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}